// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGovJgOvgFz40x_2OK-3gsi2xXKzAp6jc',
    appId: '1:96301688278:web:27348e4cde7d8af1faf077',
    messagingSenderId: '96301688278',
    projectId: 'inventariofarmacia-b7f48',
    authDomain: 'inventariofarmacia-b7f48.firebaseapp.com',
    storageBucket: 'inventariofarmacia-b7f48.firebasestorage.app',
    measurementId: 'G-VWLJV1RG0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWyaXLHDFS_j83QG8fo2CrZiK-4Aq8Bx8',
    appId: '1:96301688278:android:62114149ab3eef8ffaf077',
    messagingSenderId: '96301688278',
    projectId: 'inventariofarmacia-b7f48',
    storageBucket: 'inventariofarmacia-b7f48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPXAr_VjGiIBCeHHln8P6ZRuvKbWfcpT0',
    appId: '1:96301688278:ios:86d72ee88a777795faf077',
    messagingSenderId: '96301688278',
    projectId: 'inventariofarmacia-b7f48',
    storageBucket: 'inventariofarmacia-b7f48.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPXAr_VjGiIBCeHHln8P6ZRuvKbWfcpT0',
    appId: '1:96301688278:ios:86d72ee88a777795faf077',
    messagingSenderId: '96301688278',
    projectId: 'inventariofarmacia-b7f48',
    storageBucket: 'inventariofarmacia-b7f48.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGovJgOvgFz40x_2OK-3gsi2xXKzAp6jc',
    appId: '1:96301688278:web:1f1e02c7dc616bd4faf077',
    messagingSenderId: '96301688278',
    projectId: 'inventariofarmacia-b7f48',
    authDomain: 'inventariofarmacia-b7f48.firebaseapp.com',
    storageBucket: 'inventariofarmacia-b7f48.firebasestorage.app',
    measurementId: 'G-9170P18PDY',
  );
}
